#!/bin/bash
#
#+Hash functions.
#+
#+Copyright (C) 2020  David Hobach  LGPLv3
#+0.5

#map: algorithm --> program
declare -gA BLIB_HASH_PROGRAMS=(
	["md5"]="md5sum"
	["sha1"]="sha1sum"
	["sha224"]="sha224sum"
	["sha256"]="sha256sum"
	["sha384"]="sha384sum"
	["sha512"]="sha512sum"
	["crc"]="cksum"
	["blake2"]="b2sum"
)

#+b_hash_file [file] [algorithm]
#+Compute the hash of the given file.
#+[file]: Full path to the file.
#+[algorithm]: Algorithm to use. Currently supported: md5|sha1|sha224|sha256|sha384|sha512|crc|blake2 (default: md5).
#+returns: The hash of the given file.
#+@B_E
function b_hash_file {
local file="$1"
local algo="${2:-"md5"}"

local prog="${BLIB_HASH_PROGRAMS["$algo"]}"
[ -z "$prog" ] && B_ERR="Unsupported algorithm: $algo" && B_E

#NOTE: we prefer runtime dependencies here in order to support systems that only have a few of the programs installed
 b_deps "$prog"

local out=
out="$($prog "$file")" || { B_ERR="Failed to execute $prog." ; B_E }
echo "${out%% *}"
}

#+b_hash_str [string] [algorithm]
#+Compute the hash of the given string.
#+[string]: String which to compute the hash for.
#+[algorithm]: Algorithm to use. Currently supported: md5|sha1|sha224|sha256|sha384|sha512|crc|blake2 (default: md5).
#+returns: The hash of the given string.
#+@B_E
function b_hash_str {
local str="$1"
local algo="${2:-"md5"}"

local prog="${BLIB_HASH_PROGRAMS["$algo"]}"
[ -z "$prog" ] && B_ERR="Unsupported algorithm: $algo" && B_E

#NOTE: we prefer runtime dependencies here in order to support systems that only have a few of the programs installed
 b_deps "$prog"

local out=
out="$($prog <<< "$str")" || { B_ERR="Failed to execute $prog." ; B_E }
echo "${out%% *}"
}
