name: Run blib tests

on: [push, workflow_dispatch]

permissions:
  contents: read
  pull-requests: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt -y install pandoc texlive-latex-base texlive-latex-recommended shellcheck curl

    - name: Install bats
      run: |
        cd bats/
        tar -xvf bats-core.tar.gz
        cd bats-core
        sudo ./install.sh /usr
        cd ../../

    - name: Install blib
      run: sudo ./installer install

    - name: Configure the test environment
      run: sudo cp .github/user_test_data.bash /usr/lib/blib/tests/

    - name: Test blib
      run: blib test

    - name: Uninstall blib
      run: sudo ./installer uninstall

    - name: Make sure blib is uninstalled
      run: '[ ! -e /usr/lib/blib ]'
